
# Build options (I think)
LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
NKRO_ENABLE = yes
DEBOUNCE_TYPE = eager_pk
RGB_MATRIX_ENABLE = WS2812

# build options that are disabled.
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
OLED_DRIVER_ENABLE = no
# Do not enable SLEEP_LED_ENABLE. It uses the same timer as BACKLIGHT_ENABLE
